version: "3.9"
services:
  notifications:
    build: .
    volumes:
      - ./settings.json:/pthd-notifications/settings.json
    expose:
      - '3030'
    env_file:
      - ./local.env
    restart: unless-stopped
    depends_on:
      - "redis"
    profiles:
      - "application"
  redis:
    image: redis:7.2.1
    ports:
      - "6379"
    expose:
      - "6379"